apiVersion: v1
kind: ConfigMap
metadata:
  name: phpldapadmin-config
  namespace: hr-app
data:
  env.yaml: |
    PHPLDAPADMIN_LDAP_HOSTS:
      - ldaps://DC01.corp.local:
          login:
            attr: "samaccountname"
            bind_id: "%s@corp.local"
          server:
            base: "DC=corp,DC=local"
            port: 636