apiVersion: v1
kind: Service
metadata:
  name: phpldapadmin
  namespace: hr-app
  labels:
    app: phpldapadmin
spec:
  type: NodePort
  selector:
    app: phpldapadmin
  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: 30080
