name: Terraform CI

on:
  push:
    branches: main
  pull_request:
    branches: main

permissions:
  id-token: write
  contents: read

jobs:
  terraform-main:
    name: Main - Fmt / Validate
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: main

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-tf-ci
          aws-region: eu-central-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "~> 1.14"

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init -backend-config="profile=" -input=false

      - name: Terraform Validate
        run: terraform validate


  terraform-bootstrap:
    name: Bootstrap - Fmt / Validate
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bootstrap

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-tf-ci
          aws-region: eu-central-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "~> 1.14"

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate